[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
line_length = 120

[tool.pytest.ini_options]
addopts = "-ra -v --durations=5 --cov=pycairo_util"

# Coverage ----------------------------------------------
## http://coverage.readthedocs.io/en/latest/config.html
[tool.coverage.run]
branch = true
source = ["pycairo_util"]
data_file = ".coverage.unittest"
omit = [
    "*/site-packages/*",
    "__init__.py",
    "*__init__.py",
    "app.py",
    "main.py",
    "*/test/*",
    "*/tests/*",
    "*/test_*",
    "*_test.py",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if self.debug",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
]
